#!/usr/bin/env python3
"""
Generate secure secrets for Octa Music production deployment.
Run this script to generate all required secret keys.
"""

import secrets
import string

def generate_secret_key(length=32):
    """Generate a secure random secret key."""
    return secrets.token_hex(length)

def generate_password(length=24):
    """Generate a secure random password."""
    alphabet = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(secrets.choice(alphabet) for _ in range(length))
    return password

print("="*70)
print(" Octa Music - Production Secrets Generator")
print("="*70)
print()
print("Copy these values to your GitHub Secrets and Render Environment Variables")
print()

print("--- REQUIRED SECRETS ---")
print()

print("SECRET_KEY (Flask session encryption):")
secret_key = generate_secret_key(32)
print(f"  {secret_key}")
print()

print("--- MONGODB SETUP ---")
print()
print("1. Create MongoDB Atlas account: https://www.mongodb.com/cloud/atlas/register")
print("2. Create a FREE cluster (M0)")
print("3. Create database user with password")
print("4. Whitelist IP: 0.0.0.0/0")
print("5. Get connection string and replace <password>:")
print()
print("MONGODB_URI:")
print("  mongodb+srv://octa_music_user:<password>@cluster0.xxxxx.mongodb.net/octa_music?retryWrites=true&w=majority")
print()
print("Example with placeholder:")
mongodb_placeholder = f"mongodb+srv://octa_music_user:REPLACE_WITH_YOUR_PASSWORD@cluster0.xxxxx.mongodb.net/octa_music?retryWrites=true&w=majority"
print(f"  {mongodb_placeholder}")
print()

print("--- EMAIL CONFIGURATION ---")
print()
print("Choose ONE option:")
print()
print("Option A - Gmail (Recommended):")
print("  1. Enable 2FA on Gmail account")
print("  2. Generate App Password: https://myaccount.google.com/apppasswords")
print("  3. Use these settings:")
print()
print("  MAIL_SERVER=smtp.gmail.com")
print("  MAIL_PORT=587")
print("  MAIL_USE_TLS=True")
print("  MAIL_USERNAME=your-email@gmail.com")
print("  MAIL_PASSWORD=<16-character-app-password>")
print("  MAIL_DEFAULT_SENDER=your-email@gmail.com")
print()
print("Option B - Outlook:")
print("  MAIL_SERVER=smtp-mail.outlook.com")
print("  MAIL_PORT=587")
print("  MAIL_USE_TLS=True")
print("  MAIL_USERNAME=your-email@outlook.com")
print("  MAIL_PASSWORD=<your-account-password>")
print("  MAIL_DEFAULT_SENDER=your-email@outlook.com")
print()

print("--- OTHER SETTINGS ---")
print()
print("FRONTEND_URL:")
print("  Production: https://octa-music.onrender.com")
print("  Development: http://localhost:5000")
print()
print("SESSION_COOKIE_SECURE:")
print("  Production: True")
print("  Development: False")
print()
print("APP_ENV:")
print("  Production: production")
print("  Development: development")
print()

print("="*70)
print(" Summary of Required Secrets")
print("="*70)
print()
print("GitHub Secrets to add:")
print("  1. SECRET_KEY")
print("  2. MONGODB_URI")
print("  3. MAIL_USERNAME")
print("  4. MAIL_PASSWORD")
print("  5. MAIL_DEFAULT_SENDER")
print("  6. MAIL_SERVER")
print("  7. MAIL_PORT")
print("  8. MAIL_USE_TLS")
print()
print("Render Environment Variables to add (same as GitHub + these):")
print("  9. APP_ENV=production")
print(" 10. SESSION_COOKIE_SECURE=True")
print(" 11. FRONTEND_URL=https://octa-music.onrender.com")
print(" 12. PERMANENT_SESSION_LIFETIME=4800")
print(" 13. REMEMBER_ME_DURATION=2592000")
print()
print("Already configured (don't change):")
print("  - SPOTIPY_CLIENT_ID")
print("  - SPOTIPY_CLIENT_SECRET")
print("  - RENDER_API_KEY")
print("  - RENDER_SERVICE_ID")
print()
print("="*70)
print(" Next Steps")
print("="*70)
print()
print("1. Set up MongoDB Atlas (if not done): https://www.mongodb.com/cloud/atlas/register")
print("2. Configure email service (Gmail or Outlook)")
print("3. Add all secrets to GitHub: https://github.com/Pedro-Accarini/octa-music/settings/secrets/actions")
print("4. Add all environment variables to Render: https://dashboard.render.com/web/srv-d03h38idbo4c738clsag")
print("5. Update .env file for local testing")
print("6. Test locally: python3 src/main.py")
print("7. Deploy to production")
print()
print("For detailed instructions, see: PRODUCTION_DEPLOYMENT_CHECKLIST.md")
print()
