name: "CI Checks"
description: "Integration workflow for comum CI tasks"

inputs:
  python-version:
    description: "Python version"
    required: true
    default: "3.8"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run all tests with coverage
      id: run-tests
      shell: bash
      run: |
        pytest tests/ --cov=src --cov-report=term --cov-report=xml --cov-report=html -v > test_results.log 2>&1
        status=$?
        if [ $status -ne 0 ]; then
          echo "Tests failed! Printing test_results.log:" 
          cat test_results.log
          exit 1
        else
          echo "All tests passed."
        fi
        result=$(tail -n 20 test_results.log)
        echo "test-results<<EOF" >> $GITHUB_OUTPUT
        echo "$result" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          coverage.xml
          htmlcov/
          
    - name: Archive test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test_results.log
