name: "CI Checks"
description: "Integration workflow for common CI tasks"

inputs:
  python-version:
    description: "Python version"
    required: true
    default: "3.10"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      id: unit-tests
      shell: bash
      run: |
        pytest ./tests/test_main.py -v > result.log 2>&1
        status=$?
        if [ $status -ne 0 ]; then
          echo "❌ Unit tests failed! Printing result.log:" 
          cat result.log
          exit 1
        else
          echo "✅ All unit tests passed."
        fi
        result=$(tail -n 10 result.log)
        echo "unit-tests<<EOF" >> $GITHUB_OUTPUT
        echo "$result" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Archive code unit tests results
      uses: actions/upload-artifact@v4
      with:
        name: unit-tests-results
        path: result.log
